matrix:
  include:
  - language: python
    python: "3.6"
    script:
      - python -m unittest discover -s src/

  - language: node_js
    node_js: "12.16.1"
    install:
      - npm install
    script:
      - npm test