matrix:
  include:
  - language: python
    python: "3.6"
    install:
      - pip install -r requirements.txt
    script:
      - pytest

  - language: node_js
    node_js: "12.16.1"
    script:
      - npm test